# This workflow builds and releases the Electron app for each platform (Linux, macOS, Windows)
name: Release

on:
  push:
    tags:
      - 'v*'
      -

permissions:
  contents: write
  actions: read

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0' # The version of Node.js I used during the development of this app
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and publish
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            npm run dist:linux
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run dist:win
          else
            npm run dist:mac
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}